MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "Res5ROIHeadsExtraNorm"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    NORM: "SyncBN"
TEST:
  PRECISE_BN:
    ENABLED: True
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.05
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 180000
  MOMENTUM: 0.9
  NESTEROV: false
  REFERENCE_WORLD_SIZE: 0
  WARMUP_FACTOR: 0.0001
  WARMUP_ITERS: 10000
  WARMUP_METHOD: linear
